### ISSUE TITLE
Chapter - Missing.

### ISSUE THREAD

**Issue by Max-Enrik** [dyphire/mpv-scripts#10]
The first chapter is missing.
And needed to write the chapter name that doesn't save as I chose a name.

**Comment by dyphire** [comment]
Missing necessary information, will be ignored.

**Comment by Max-Enrik** [comment]
1. Time Stamp - `00:04:17.708 Chapter 01`
2. I need it to ask for a title - `ask_for_title = true`
3. But it doesn't **save the title name**.

**Comment by dyphire** [comment]
Still unable to reproduce. 
Is there still a issue with using the latest script of [chapter-make-read.lua](https://github.com/dyphire/mpv-scripts/blob/main/chapter-make-read.lua), [chapter-list.lua](https://github.com/dyphire/mpv-scripts/blob/main/chapter-list.lua)?

**Comment by Max-Enrik** [comment]
The issue occurs when the option is yes.
And I turned it off to avoid the issue.

```
# Settings For SimpleHistory 1.1.5
mark_history_as_chapter=no
```
After it is turned off (/no) no more problem.
