### ISSUE TITLE
track-list.lua - "%20" showing instead of space.

### ISSUE THREAD

**Issue by LampPrinter** [dyphire/mpv-scripts#13]
If I drag and drop an external subtitle then "%20" is shown instead of space.

![CleanShot - Married  with Children (1987) - S06E20 - Hi I Q  (480p DVD x265 Silence) mkv - mpv (mpv) - 13 April 2023 at 17 31 23](https://user-images.githubusercontent.com/7559328/231752630-2c51deec-4796-4d1b-a835-bf1a5e63e06e.png)

**Comment by LampPrinter** [comment]
The subtitle should be named differently than the video file.
Please see the video.

https://user-images.githubusercontent.com/7559328/231874330-9be7938b-11b9-44c0-8caa-bd125e487040.mp4

**Comment by dyphire** [comment]
Is the name displayed correctly in the subtitle menu of uosc.lua? If the names are the same, it is likely that the issue is with mpv, I suspect that your mpv version is a bit old and not built on the git master.

**Comment by LampPrinter** [comment]
Yeah, UOSC also has this issue. Probably something on their end. My mpv build is latest.

**Comment by dyphire** [comment]
Still can't reproduce, the problem is not related to the script. it is likely an issue with mpv.

https://user-images.githubusercontent.com/61936050/231910329-ffbcffe3-6dac-4d5b-8d65-46746e34825c.mp4
