### ISSUE TITLE
chapter-make-read.lua - Fails with realistic amount and names for chapters - Works with minimal chapter file

### ISSUE THREAD

**Issue by porg** [dyphire/mpv-scripts#14]
## Reproduction
1. Installed `chapter-make-read.lua` by moving it into `~/.config/mpv/scripts/`
2. Put sidecar chapter file next to video file:
    - `EVM.m4v` (49m 28s, no chapters in metadata)
    - `EVM.m4v.chp` (UTF-8, created with TextEdit)

Result: Chapter loading ✅ works from very minimal but unrealistic chapter file ❌  but fails with realistic chapter file.

## ✅ Very minimal but unrealistic chapter file
- 4 chapters
- 0:00:00 til 0:40:00
- Chapters max 3 words, ASCII `[A-Za-z ]` only, no punctuation whatsoever

## ❌ My realistic chapter file
- 32 chapters
- 0:00:00 til 0:31:37
- Longest line 92 characters (timestamp plus chapter text)
- Used characters: `[A-Za-z ]` (ASCII only!) and several punctuation characters such as `' " , . : … • & / ( )`

## Investigation
- Tried a lot of trial and error. Could not find the root cause.
- Performed several test rounds
  - 0. Start with original chapter file
  - 1. Reduce a certain character from the file (e.g. hyphen, dot, colon, ampersand, ...) by find/replace.
  - 2. Save file.
  - 3. Reopen mpv with that file.
  - 4. Quit mpv again
  - Go back to 1. Several times
- Then also tried to cut the maximum line length to e.g. 20 characters.
- Checked that my filestamps are a continuum (no timestamp earlier than the previous timestamp)
- All helped nothing. Was left clueless.

## Environment
- macOS 11 Big Sur
- mpv 0.35.0 (installed via [brew](https://brew.sh) package manager)

### Notes
- The `.txt` extension was only added to be accepted as an attachment on Github
- During playback attempt the respective files were of course renamed to `EVM.m4v.chp` to act as the sidecar file to `EVM.m4v.chp`

### Files
- [EVM-mini-version-works.m4v.chp.txt](https://github.com/dyphire/mpv-scripts/files/11971306/EVM-mini-version-works.m4v.chp.txt)
- [EVM-original-with-punctuation.m4v.chp.txt](https://github.com/dyphire/mpv-scripts/files/11971307/EVM-original-with-punctuation.m4v.chp.txt)

**Comment by dyphire** [comment]
Fix by commit https://github.com/dyphire/mpv-scripts/commit/bc6763e87f3da0467caf12709b5dde85988f8f18, please test whether it works for you.
