### ISSUE TITLE
chapter-make-read.lua: Autodetection of sidecar file also for basename.chp 

### ISSUE THREAD

**Issue by porg** [dyphire/mpv-scripts#15]
- **Currently:** The sidecar is the full file name including the video suffix + the `.chp` extension
- **Proposed**: It should also detect the file name without the video suffix + the `.chp` extension
  - Design rationale: That's common for subtitle files like `.SRT`, see `mpv` option [--options-sub-auto](https://mpv.io/manual/stable/#options-sub-auto)
  - In the macOS Finder the handling of files with two file extension is a bit inconvenient when renaming files. Would prefer `.chp` as the sole extension for this reason too.
- **Note:** The current sidecar file detection pattern shall remain too.
  - That way per use case you can be either ultra specific or more tolerant/flexible with how you name your chapter files, e.g.
    - `vid.mp4` + `vid.mp4.chp` + `vid.avi` + `vid.avi.chp` all matching uniquely
    - whereas `vid.chp` would be a sidecar file to both `vid.mp4` and `vid.avi`

**Comment by dyphire** [comment]
This is an old behavior that has been deprecated in the commit https://github.com/dyphire/mpv-scripts/commit/5b86d13527a6f41b24985dae1d963f29a143c310. The reason for adding extension matching is to avoid incorrect matching between files with the same name but different extensions.

> whereas `vid.chp` would be a sidecar file to both `vid.mp4` and `vid.avi`

I completely cannot imagine the existence of such usage scenarios, why the same content retains two or more different files. This is not a real use case.

**Comment by porg** [comment]
Hi, exactly that's why I stated it: Having both `vid.mp4` and `vid.avi` is quite unlikely!
- At most if the one is a (container of quality) conversion of the other, and then `vid.chp` most likely fits both.
- Hence no need to be ultra specific with `basename.vidSuffix.chp`. 
- `basename.chp` will match correctly in 99% of the use cases.
- And in some GUI file managers (e.g. macOS Finder) the handling of two file suffixes is a bit inconvenient (on every rename operation asks you whether to reduce the extension to only one of the both).

So, please re-introduce the old behavior you mentined, at least as an additional way.

**Comment by porg** [comment]
- Thanks for fixing #17
- Tackling this very issue here by re-introducing `basename.chp` as an additional valid filename pattern, and **Chapter files in mpv on the Mac** would work really fine then.
  - With the two suffixes the Mac Finder annoys all the time on each naming operation.
- #16 would only be a cherry on the top of the cake 😉 nice to have one day, but also ok without it.

**Comment by dyphire** [comment]
> Tackling this very issue here by re-introducing `basename.chp` as an additional valid filename pattern, and Chapter files in mpv on the Mac would work really fine then.

Yes, I am considering re implementing it. The only issue is whether the two modes need to coexist, which will result in multiple detections of the existence of chapter files.

Considering that both modes can meet over 99% of usage scenarios, I tend to add a new option that allows users to choose the matching mode to use.

**Comment by porg** [comment]
✅ Tested b0cd966 and it works:
- Ran it with `basename_with_ext = false` and then `basename.chp` was correctly read in as the chapter sidecar file for `basename.vidSuffix` with vidSuffixes  `avi | mkv | mp4` all having worked well.
