### ISSUE TITLE
[track-list.lua] Some feature requests

### ISSUE THREAD

**Issue by KonoVitoDa** [dyphire/mpv-scripts#20]
- Don't count _None_ track in the total number of tracks. If possible, setting its ID to 0 would be a good solution I suppose. ```OR:``` Show track numbering on the list, to make it more easy and intuitive to figure out what's the actual track ID.
- Don't show ```<TrackType> <TrackID>``` when track has no name, just left it empty. I mean: I don't want to see tracks appearing like ```Audio 01``` if the audio track has no name.
- Option to show extension in uppercase, instead of language.

**Comment by dyphire** [comment]
> * Don't count _None_ track in the total number of tracks. If possible, setting its ID to 0 would be a good solution I suppose. `OR:` Show track numbering on the list, to make it more easy and intuitive to figure out what's the actual track ID.

https://github.com/dyphire/mpv-scripts/commit/5eecbe7b74fbc98bccac9381466d3c4011c9041f
> * Don't show `<TrackType> <TrackID>` when track has no name, just left it empty. I mean: I don't want to see tracks appearing like `Audio 01` if the audio track has no name.
> * Option to show extension in uppercase, instead of language.

Not interested in this, you can modify the script according to your own ideas to implement them.

**Comment by KonoVitoDa** [comment]
> 5eecbe7

Now it's very good, thank you!



> Not interested in this, you can modify the script according to your own ideas to implement them.

I'll try to figure out how to do it.
