### ISSUE TITLE
[track-list.lua] Bug Report + Feature Request + Question

### ISSUE THREAD

**Issue by KonoVitoDa** [dyphire/mpv-scripts#23]
- If subtitle's filename contains video's filename, this part is trimmed and ignored in the track list; and in the same way if the sub and video filenames are identical, no track name is shown at all. Is this a bug or is it on purpose? If it's the second, what can I do to always show the full track name?
- A second keybinding press should hide the list, not reopen it. I'd like to press , for example, Ctrl+s to open the subs list and press it again to hide it. It would be much more intuitive than having to press ESC.
- How to avoid showing these generic track names (Sub 11) for tracks with no name? Thus bringing back the old script behavior.

Screenshots for reference:
![Screenshot (103)](https://github.com/dyphire/mpv-scripts/assets/51209382/6106f2bb-1b9b-4ad6-94d1-4bc63dd6ff50)
![image](https://github.com/dyphire/mpv-scripts/assets/51209382/564f1a91-9c66-4fd4-94d0-dc297fdd51ae)

**Comment by dyphire** [comment]
> If subtitle's filename contains video's filename, this part is trimmed and ignored in the track list; and in the same way if the sub and video filenames are identical, no track name is shown at all. Is this a bug or is it on purpose? If it's the second, what can I do to always show the full track name?
How to avoid showing these generic track names (Sub 11) for tracks with no name? Thus bringing back the old script behavior.

You can achieve this by commenting out the following content in the script:
https://github.com/dyphire/mpv-scripts/blob/6e8ba340c6d4c5451084a3d144b5c2a2565308c0/track-list.lua#L134-L137
https://github.com/dyphire/mpv-scripts/blob/6e8ba340c6d4c5451084a3d144b5c2a2565308c0/track-list.lua#L141-L144

> A second keybinding press should hide the list, not reopen it. I'd like to press , for example, Ctrl+s to open the subs list and press it again to hide it. It would be much more intuitive than having to press ESC.

No, this is a limitation of how scripts work, not a bug, and cannot be implemented.

**Comment by KonoVitoDa** [comment]
> You can achieve this by commenting out the following content in the script:

Thanks, it worked. But the comma before the language code remains. I had the impression that it wasn't like that before, but checking the old versions it seems like it always was. Isn't there an easy way to conditionally add the comma only when the track has a name?

**Comment by dyphire** [comment]
> > You can achieve this by commenting out the following content in the script:
> 
> Thanks, it worked. But the comma before the language code remains. I had the impression that it wasn't like that before, but checking the old versions it seems like it always was. Isn't there an easy way to conditionally add the comma only when the track has a name?

This is because when you comment out the code above, the title may be empty, which will not appear in the original code. For this, you also need to modify the following code:
https://github.com/dyphire/mpv-scripts/blob/1596f85ceea069159ed20e9173da614530348511/track-list.lua#L156-L157

**Comment by dyphire** [comment]
> A second keybinding press should hide the list, not reopen it. I'd like to press , for example, Ctrl+s to open the subs list and press it again to hide it. It would be much more intuitive than having to press ESC.

Implement it in the latest commit

**Comment by KonoVitoDa** [comment]
> mplement it in the latest commit

Thanks!
