### ISSUE TITLE
Help wanted , installation 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [dyphire/mpv-scripts#30]
Hi, I want to install chapter-list.lua. as you mentioned it needs the scroll-list.lua. 

I have the mpv-portable folder, I've created the 

script-module and put the script in it, but nothing works. 

Can you guide me step by step what to do?

**Comment by dyphire** [comment]
You need to put scroll-list.lua into the `script-modules` folder and then chapter-list.lua into `scripts` folder.
