### ISSUE TITLE
Chapter files whose name contains a colon don't work with `chapter-make-read.lua`

### ISSUE THREAD

**Issue by agreselin** [dyphire/mpv-scripts#32]
Hi, I've noticed that if a filename contains colons then it doesn't work work with `chapter-make-read.lua`. E.g. I have `Megadeth: Tiny Desk Concert.mkv` and `Megadeth: Tiny Desk Concert.chp`. `chapter-make-read.lua` ignores the chapters until I rename both files replacing the colon with something else. Is it something that can be fixed in the script?

**Comment by dyphire** [comment]
On Windows, special characters such as `\/:%?` are illegal characters that cannot be used in filenames. This was specially handled in the previous code. Unexpectedly broken usage on Unix platforms, fixed.

**Comment by agreselin** [comment]
Great, thanks!
