### ISSUE TITLE
大佬，请教个问题，你这版本的mpv怎么配置才能调用rtx视频增强里的hdr功能呢？

### ISSUE THREAD

**Issue by guruguruame** [dyphire/mpv-scripts#34]
我改了一下mpv.conf里的配置，VSR是能用了，但hdr总是处于非活动状态。这是我配置文件请你过目。
[mpv.txt](https://github.com/user-attachments/files/18256851/mpv.txt)这玩意其实是mpv.conf，为了上传我改了后缀
![6D4ACEA27375D8CF7F2819641C459C11](https://github.com/user-attachments/assets/8fdb38bc-5d96-435f-8793-b28bd5bb60cd)
如果您能解决问题感激不尽

**Comment by dyphire** [comment]
不要在此存储库下打开无关话题，RTX HDR 的使用参考 https://github.com/mpv-player/mpv/pull/14901
