### ISSUE TITLE
[Feature Request] Mediainfo add toggle keybind

### ISSUE THREAD

**Issue by LampPrinter** [dyphire/mpv-scripts#7]
At present the info stays on screen for 5 seconds. I would prefer if a toggle keybind can be added.

**Comment by dyphire** [comment]
This cannot be done at present. This is the limitation of script implementation.
https://github.com/dyphire/mpv-scripts/blob/3fe0551c723232f18b51e97675c00138ab12cbcf/mediaInfo.lua#L79-L82

I am not interested in implementing it for now.
